# Generated by Django 5.0.3 on 2024-04-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authentication',
        ),
    ]
