# Generated by Django 5.0.3 on 2024-05-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_app', '0004_customuser_delete_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='irst_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
